name: bible
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  xml: ^6.6.1
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  recase: ^4.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2874.0
  flutter_slidable: ^4.0.3
  rounded_background_text: ^0.6.0
  flutter_tailwind_colors: ^0.0.3
  equatable: ^2.0.5
  intersperse: ^2.0.0
  flutter_sticky_header: ^0.8.0
  another_flushbar: ^1.12.32
  provider: ^6.1.5+1

  port:
    git:
      url: https://github.com/JLogical-Apps/flood.git
      ref: "89a170167523e52354afe3646841e28216b9210a"
      path: packages/port/port
  utils_core:
    git:
      url: https://github.com/JLogical-Apps/flood.git
      ref: "89a170167523e52354afe3646841e28216b9210a"
      path: packages/utils/utils_core


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/strongs/
    - assets/commentary/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Italic.ttf
          style: italic